import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Next js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className=" min-h-screen bg-white dark:bg-slate-800 dark:text-white ">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
